# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2b04527c2659fe99f9b04d2cb1ed20466584840b8c7937abd1d95205057b0d2b53ff6adca5680c290f6e3c7fce959c1d0f39c039e02763010e2947e15728171

test:
  secret_key_base: 0c31dc4c4233eb16ec39e79e11097b534d38816e5e04a4af641f159ef2b335831f30c7f881c7f1fa61f708dfbd5e9231209b78ab854199505caf29617904f494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
